[package]
name = "workflow-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "db_build"

[dependencies]
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-rustls", "json", "macros", "chrono", "ipnetwork"] }
tokio = { version = "1.20.1", features = ["full"] }
async-once-cell = "0.4.2"
serde = { version = "1.0.144" }
serde_json = { version = "1.0.89", features = ["raw_value"] }
log = "0.4.17"
log4rs = { version = "1.1.1", features = ["rolling_file_appender", "console_appender", "pattern_encoder", "fixed_window_roller", "size_trigger", "threshold_filter"] }
