declare
    v_workflow text := 'workflow';
    v_executor text := 'executor';
    v_task text := 'task';
    v_job text := 'job';
begin
    call data_check.check_function_definition(v_executor, 'all_executor_workflows');
    call data_check.check_function_definition(v_workflow, 'append_task_rule');
    call data_check.check_function_definition(v_executor, 'cancel_executor');
    call data_check.check_function_definition(v_workflow, 'cancel_workflow_run');
    call data_check.check_function_definition(v_executor, 'clean_executors');
    call data_check.check_function_definition(v_executor, 'close_executor');
    call data_check.check_function_definition(v_job, 'complete_job');
    call data_check.check_function_definition(v_workflow, 'complete_task_run');
    call data_check.check_function_definition(v_workflow, 'complete_task');
    call data_check.check_function_definition(v_workflow, 'complete_workflow_run_move');
    call data_check.check_function_definition(v_workflow, 'complete_workflow_run');
    call data_check.check_function_definition(v_job, 'create_interval_job');
    call data_check.check_function_definition(v_job, 'create_scheduled_job');
    call data_check.check_function_definition(v_workflow, 'create_workflow');
    call data_check.check_function_definition(v_workflow, 'deprecate_workflow');
    call data_check.check_function_definition(v_workflow, 'fail_task_run');
    call data_check.check_function_definition(v_workflow, 'initialize_workflow_run');
    call data_check.check_function_definition(v_job, 'job_change');
    call data_check.check_function_definition(v_executor, 'next_executor');
    call data_check.check_function_definition(v_job, 'next_run_job_schedule');
    call data_check.check_function_definition(v_workflow, 'next_task');
    call data_check.check_function_definition(v_workflow, 'next_workflow');
    call data_check.check_function_definition(v_executor, 'post_executor_error_message');
    call data_check.check_function_definition(v_executor, 'register_executor');
    call data_check.check_function_definition(v_executor, 'executor_status');
    call data_check.check_function_definition(v_workflow, 'restart_workflow_run');
    call data_check.check_function_definition(v_workflow, 'retry_task');
    call data_check.check_function_definition(v_job, 'run_job');
    call data_check.check_function_definition(v_workflow, 'schedule_workflow_run');
    call data_check.check_function_definition(v_executor, 'shutdown_executor');
    call data_check.check_function_definition(v_workflow, 'start_task_run');
    call data_check.check_function_definition(v_workflow, 'start_workflow_run_move');
    call data_check.check_function_definition(v_workflow, 'start_workflow_run');
    call data_check.check_function_definition(v_job, 'valid_job_schedule');
    call data_check.check_function_definition(v_workflow, 'workflow_run_status_event');
    call data_check.check_function_definition(v_workflow, 'workflow_progress_event');
    call data_check.check_function_definition(v_task, 'workflow_tasks_check');
end;
