declare
    v_schema text := 'workflow_engine';
begin
    call data_check.check_function_definition('executor', 'all_executor_workflows');
    call data_check.check_function_definition('task', 'append_task_rule');
    call data_check.check_function_definition('executor', 'cancel_executor');
    call data_check.check_function_definition(v_schema, 'cancel_workflow_run');
    call data_check.check_function_definition('executor', 'clean_executors');
    call data_check.check_function_definition('executor', 'close_executor');
    call data_check.check_function_definition(v_schema, 'complete_job');
    call data_check.check_function_definition(v_schema, 'complete_task_run');
    call data_check.check_function_definition(v_schema, 'complete_task');
    call data_check.check_function_definition(v_schema, 'complete_workflow_run_move');
    call data_check.check_function_definition(v_schema, 'complete_workflow_run');
    call data_check.check_function_definition('job', 'create_interval_job');
    call data_check.check_function_definition('job', 'create_scheduled_job');
    call data_check.check_function_definition(v_schema, 'create_workflow');
    call data_check.check_function_definition(v_schema, 'deprecate_workflow');
    call data_check.check_function_definition(v_schema, 'fail_task_run');
    call data_check.check_function_definition(v_schema, 'initialize_workflow_run');
    call data_check.check_function_definition(v_schema, 'job_change');
    call data_check.check_function_definition('executor', 'next_executor');
    call data_check.check_function_definition(v_schema, 'next_run_job_schedule');
    call data_check.check_function_definition(v_schema, 'next_task');
    call data_check.check_function_definition(v_schema, 'next_workflow');
    call data_check.check_function_definition('executor', 'post_executor_error_message');
    call data_check.check_function_definition(v_schema, 'register_executor');
    call data_check.check_function_definition(v_schema, 'we_executor_status');
    call data_check.check_function_definition(v_schema, 'restart_workflow_run');
    call data_check.check_function_definition(v_schema, 'retry_task');
    call data_check.check_function_definition(v_schema, 'run_job');
    call data_check.check_function_definition(v_schema, 'schedule_workflow_run');
    call data_check.check_function_definition('executor', 'shutdown_executor');
    call data_check.check_function_definition(v_schema, 'start_task_run');
    call data_check.check_function_definition(v_schema, 'start_workflow_run_move');
    call data_check.check_function_definition(v_schema, 'start_workflow_run');
    call data_check.check_function_definition(v_schema, 'valid_job_schedule');
    call data_check.check_function_definition(v_schema, 'workflow_run_status_event');
    call data_check.check_function_definition(v_schema, 'workflow_progress_event');
    call data_check.check_function_definition('task', 'workflow_tasks_check');
end;
