[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6.2", features = ["postgres", "runtime-tokio-rustls"] }
serde = { version = "1.0.144" }
tokio = { version = "1.23.1", features = ["full"] }
serde_json = { version = "1.0.89" }
